// learn-code/react-Learn/week2/UmiJS/umi-app/src/pages_model_plugin/banner/list/index.tsx
import React, { useEffect, useState } from 'react';
import styles from './index.less';
import { getBannerlist } from '@/api/banner'
import { Table, Space, Button } from 'antd'
import { history } from 'umi'
import { 
  EditOutlined, 
  DeleteOutlined 
} from '@ant-design/icons'

interface IBanner {
  alt: string,
  bannerid: string,
  bannerimg: string,
  link: string
}

export default function Page() {
  const [bannerList, setBannetList] = useState([])

  useEffect(() => {
    async function getData () {
      const res = await getBannerlist()
      setBannetList(res.data)
    }
    getData()
  }, [])

  const columns = [
    {
      title: '序号',
      render: (text: string | number | boolean, record: IBanner, index: number) => <span>{ index + 1 }</span>
    },
    {
      title: '图片',
      key: 'bannerimg',
      dataIndex: 'bannerimg',
      render: (text: string, record: IBanner) => {
        return <img src={ text } style={{ width: '100px' }} alt=""/>
      }
    },
    {
      title: '操作',
      render: (text: any, record: IBanner) =>  <Space>
        <Button type="primary" onClick = { () => {
          history.push('/banner/detail/' + record.bannerid)
        } } shape="circle" icon={<EditOutlined />} />
        <Button danger shape="circle" icon={<DeleteOutlined />} />
      </Space>
    }
  ]

  return (
    <Table dataSource={ bannerList } columns={ columns }  rowKey={ item => item.bannerid } />
  );
}

// learn-code/week13/vue3-pro/src/views/banner/list.vue
<template>
  <a-table :columns="columns" :data-source="state.banner" :rowKey="getRowKey">
      <template #index="obj">
      <a>{{ obj.index + 1 }}</a>
    </template>
    <template #bannerimg="{ text }">
     <img :src="text" alt="" style="width: 60px;">
    </template>
    <template #customTitle>
      <span>
        <smile-outlined />
        Name
      </span>
    </template>
    <template #tags="{ text: tags }">
      <span>
        <a-tag
          v-for="tag in tags"
          :key="tag"
          :color="tag === 'loser' ? 'volcano' : tag.length > 5 ? 'geekblue' : 'green'"
        >
          {{ tag.toUpperCase() }}
        </a-tag>
      </span>
    </template>
    <template #action>
       <a-space>
             <a-button type="primary" ghost>编辑</a-button>
             <a-button type="danger" ghost>删除</a-button>
       </a-space>
    </template>
  </a-table>
</template>
<script lang="ts">
import { SmileOutlined } from '@ant-design/icons-vue'
import { defineComponent, reactive, onMounted, computed } from 'vue'
import { getBannerlist } from './../../api/banner'
const columns1 = [
  {
    title: '序号',
    slots: { customRender: 'index' }
  },
  {
    dataIndex: 'bannerimg',
    key: 'bannerimg',
    title: '图片地址',
    slots: { title: 'customTitle', customRender: 'bannerimg' }
  },
  {
    title: '图片的链接',
    dataIndex: 'link',
    key: 'link'
  },
  {
    title: '图片的说明',
    dataIndex: 'alt',
    key: 'alt'
  },
  {
    title: '操作',
    key: 'action',
    slots: { customRender: 'action' }
  }
]

export default defineComponent({
  setup () {
    const state = reactive({ banner: [] })
    const columns = reactive(columns1)

    // 生命周期的钩子函数
    onMounted(() => {
      getBannerlist().then(res => {
        state.banner = res.data
      })
    })
    // 计算属性
    const counter = computed(() => state.banner.length)

    const getRowKey = (row) => {
      return row.bannerid
    }

    return {
      state,
      columns,
      getRowKey,
      counter
    }
  },
  components: {
    SmileOutlined
  }
})
</script>
