// re-learn-vue/yinghua-admin/src/layout/topHeader.vue
<template>
   <a-layout-header style="background: #fff; padding: 0">
        <menu-unfold-outlined
          v-if="collapsed"
          class="trigger"
          @click="() => (collapsed = !collapsed)"
        />
        <menu-fold-outlined
          v-else
          class="trigger"
          @click="() => (collapsed = !collapsed)"
        />
      </a-layout-header>
</template>
<script setup lang="ts">
import {
    UserOutlined,
    VideoCameraOutlined,
    UploadOutlined,
    MenuUnfoldOutlined,
    MenuFoldOutlined,
  } from '@ant-design/icons-vue';
  import { defineComponent, ref } from 'vue';

  const selectedKeys = ref<string[]>(['1']);
  const collapsed = ref<boolean>(false);
</script>

// react18-learn/newssystem-ts/src/layout/TopHeader.tsx
import React, { useState } from 'react'
import { Layout } from 'antd'
import {
    MenuUnfoldOutlined,
    MenuFoldOutlined,
  } from "@ant-design/icons";
const { Header } = Layout;

export default function TopHeader() {
    const [collapsed, setCollapsed] = useState(false);
    return (
        <Header className="site-layout-background" style={{ padding: '0 16px' }}>
          {
            collapsed ? <MenuUnfoldOutlined/> : <MenuFoldOutlined/>
          }
        </Header>
    )
}
