// re-learn-vue/vue3-ts-admin/src/layout/login.vue
<template>
  <div class="login-Com">
    <div class="login-form-part">
      <div class="loginForm">
        <h1>VUE3-ADMIN</h1>
        <a-form
          :model="formState"
          name="basic"
          autocomplete="off"
          @finish="onFinish"
          @finishFailed="onFinishFailed"
        >
          <a-form-item
            name="username"
            :rules="[
              { required: true, message: '请输入用户名!' },
            ]"
          >
            <a-input v-model:value="formState.username" />
          </a-form-item>

          <a-form-item
            name="password"
            :rules="[
              { required: true, message: '请输入密码!' },
            ]"
          >
            <a-input-password v-model:value="formState.password" />
          </a-form-item>
          <a-form-item>
            <a-button style="width: 100%;" type="primary" html-type="submit">登录</a-button>
          </a-form-item>
        </a-form>
      </div>
    </div>
  </div>
</template>
<script setup>
import { reactive } from "vue";
import { useStore } from 'vuex'
import { useRouter } from 'vue-router'
const formState = reactive({
  username: "",
  password: "",
  remember: true,
});
const store = useStore()
const router = useRouter()

const onFinish = (values) => {
  console.log("Success:", values);
  store.dispatch('saveUserInfoAction', { username: formState.username }).then(res => {
      console.log(res)
      if(res.code === 200) {
          //登录成功
          router.push({ name: 'home' })
      }
  })

};

const onFinishFailed = (errorInfo) => {
  console.log("Failed:", errorInfo);
};
</script>
<style lang="scss" scoped>
.login-Com {
  width: 100%;
  height: 100%;
  background: url("../assets/loginBg.jpeg") no-repeat center;
  background-size: cover;
  .login-form-part {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    box-shadow: 0 0 5px #baa1ff;

    .loginForm {
      width: 350px;
      height: 320px;
      padding: 50px;
      background: white;
      border-radius: 6px;
      .comTitle {
        text-align: center;
        color: #70727c;
        margin-bottom: 50px;
      }
    }
  }
}
</style>

// react18-learn/newssystem-ts/src/views/login/Login.tsx
import React from 'react'
import { Button, message, Form, Input } from 'antd'
import { useNavigate } from 'react-router-dom'
import './login.scss'
import axios from 'axios'

const Login = () =>  {
    const navigate = useNavigate();
    const onFinish = (values: any) => {
        Promise.all([
            axios.get('user1.json'),
            axios.get('routeRight.json')
        ]).then(res => {
            if(res[0].data[values.username]) {
                message.success('登录成功')
                localStorage.setItem('token', JSON.stringify(res[0].data[values.username]));
                localStorage.setItem('rights', JSON.stringify(res[1].data[values.username]));
                navigate('/home')
            } else {
                message.error('该用户不存在')
            }
            
        })
      };
    
      const onFinishFailed = (errorInfo: any) => {
        console.log('Failed:', errorInfo);
      };
    return (
        <div className="loginForm-Container">
            <div className="login-part">
                <h1 className="loginForm-title">聚合支付管理系统</h1>
            <Form
                name="basic"
                onFinish={onFinish}
                onFinishFailed={onFinishFailed}
                autoComplete="off"
                >
                <Form.Item
                    name="username"
                    rules={[{ required: true, message: '请输入用户名!' }]}
                >
                    <Input placeholder="请输入用户名!" />
                </Form.Item>

                <Form.Item
                    name="password"
                    rules={[{ required: true, message: '请输入密码!' }]}
                >
                    <Input.Password placeholder="请输入密码!" />
                </Form.Item>

                <Form.Item>
                    <Button type="primary" htmlType="submit" style={{ width: '100%' }}>
                    登录
                    </Button>
                </Form.Item>
                </Form>
            </div>
        </div>
    )
}

export default Login
